src/SponsorsManager.sol

- Do not put onDistribution period to 1 if it is not necessary 
Before
After

feat: turn on onDistributionPeriod only on paginations

---

.env.31.qa.dapp
deployments/testnet_qa_dapp/contract_addresses.json

- include configuration used for dApp QA deployment
- dApp QA env requires contracts configured differently

chore: deploy contracts for qa dapp

---

foundry.toml
test/BaseTest.sol
test/SponsorsManager.t.sol
test/invariant/AllocateInvariants.t.sol
test/invariant/BaseInvariants.sol
test/invariant/BuilderInvariants.t.sol
test/invariant/EpochInvariants.t.sol
test/invariant/RewardInvariants.t.sol
test/invariant/handlers/AllocateHandler.sol
test/invariant/handlers/BaseHandler.sol
test/invariant/handlers/BuilderHandler.sol
test/invariant/handlers/DistributionHandler.sol
test/invariant/handlers/EpochHandler.sol
test/invariant/handlers/IncentivizeHandler.sol
test/invariant/handlers/TimeManager.sol

- Add invariant tests
Some findings fixed here #81 
- [TOK-279](https://rsklabs.atlassian.net/browse/TOK-279)

TOK-279: add invariant tests

---

.github/workflows/docgen.yml

Modifies and fixes the docgen workflow, to only be run manually. 
PR review trigger was increasing the merge conflics and it doesn't adds much value.
- manually run the workflow
- https://rsklabs.atlassian.net/browse/TOK-445

[TOK-445] fix docgen workflow

---

docs/src/src/BuilderRegistry.sol/abstract.BuilderRegistry.md
docs/src/src/EpochTimeKeeper.sol/abstract.EpochTimeKeeper.md
docs/src/src/RewardDistributor.sol/contract.RewardDistributor.md
docs/src/src/SponsorsManager.sol/contract.SponsorsManager.md
docs/src/src/gauge/Gauge.sol/contract.Gauge.md
docs/src/src/gauge/GaugeBeacon.sol/contract.GaugeBeacon.md
docs/src/src/gauge/GaugeFactory.sol/contract.GaugeFactory.md
docs/src/src/governance/ChangeExecutorRootstockCollective.sol/contract.ChangeExecutorRootstockCollective.md
docs/src/src/governance/GovernanceManager.sol/contract.GovernanceManager.md
docs/src/src/governance/Governed.sol/abstract.Governed.md
docs/src/src/governance/Upgradeable.sol/abstract.Upgradeable.md
docs/src/src/governance/changerTemplates/WhitelistBuilderChangerTemplate.sol/contract.WhitelistBuilderChangerTemplate.md
docs/src/src/interfaces/IChangeContractRootstockCollective.sol/interface.IChangeContractRootstockCollective.md
docs/src/src/interfaces/IChangeExecutorRootstockCollective.sol/interface.IChangeExecutorRootstockCollective.md
docs/src/src/interfaces/IGovernanceManager.sol/interface.IGovernanceManager.md
docs/src/src/interfaces/ISponsorsManager.sol/interface.ISponsorsManager.md
docs/src/src/libraries/UtilsLib.sol/library.UtilsLib.md
docs/src/src/mvp/ChangeExecutorRootstockCollective.sol/contract.ChangeExecutorRootstockCollective.md
docs/src/src/mvp/Governed.sol/abstract.Governed.md
docs/src/src/mvp/IChangeExecutorRootstockCollective.sol/interface.IChangeExecutorRootstockCollective.md
docs/src/src/mvp/SimplifiedRewardDistributorRootstockCollective.sol/contract.SimplifiedRewardDistributorRootstockCollective.md
docs/src/src/mvp/Upgradeable.sol/abstract.Upgradeable.md
src/SponsorsManager.sol
test/Gauge.t.sol
test/SponsorsManager.t.sol

- Claim all rewards by asset
- There was no option to claim rewards by individual asset
- Unit tests have been updated & added, and all previous flows should work as before.
- [TOK-365](https://rsklabs.atlassian.net/browse/TOK-365)

TOK-365: claim rewards by asset

---

src/SponsorsManager.sol
test/BaseTest.sol
test/Gauge.t.sol
test/integration/SkipDistribution.t.sol
test/integration/SupportAndDistribute.t.sol

Add integration tests to cover scenarios where distribution is skipped
- [Task](https://rsklabs.atlassian.net/browse/TOK-136)

TOK-136: Add integration tests for skipping distribution

---

src/BuilderRegistryRootstockCollective.sol
test/MigrateBuilder.t.sol

- Allow builders migration from MVP to v2
- Unit testing
- [Jira Ticket](https://rsklabs.atlassian.net/jira/software/projects/TOK/boards/267?assignee=712020%3A42dabdd3-0b32-4060-be21-62cfd46a1751&selectedIssue=TOK-353)

Tok 353/migration to v2

---

src/RewardDistributorRootstockCollective.sol

removes unused field
it was depracated when GovernorManagar was introduced
- Everything should keep working as it is before

Remove legacy unused field

---

src/BackersManagerRootstockCollective.sol
src/BuilderRegistryRootstockCollective.sol
src/governance/changerTemplates/CommunityApproveBuilderChangerTemplateRootstockCollective.sol
test/BackersManagerRootstockCollective.t.sol
test/BaseTest.sol
test/BuilderRegistryRootstockCollective.t.sol
test/MigrateBuilder.t.sol
test/governance/changers/CommunityApproveBuilderChanger.t.sol
test/invariant/BuilderInvariants.t.sol
test/invariant/handlers/BuilderHandler.sol

The whitelist process requires KYC approval and community approval. Currently the `whitelistBuilder` function handles the community approval, so this task is to rename that and everything related.
- The flow itself didn't change, just the naming so existing tests still work
- Task: [TOK-453](https://rsklabs.atlassian.net/browse/TOK-453)

TOK-453: Renaming in whitelisting flow

---

src/BuilderRegistryRootstockCollective.sol
test/RewardDistributorRootstockCollective.t.sol

- Address issue RSCR-07 raised in security report
- [Task](https://rsklabs.atlassian.net/browse/TOK-483)

[TOK-483]  RSCR-07: remove unused errors

---

src/gauge/GaugeRootstockCollective.sol
test/GaugeRootstockCollective.t.sol

- There is a requirement to show estimated rewards left to earn for backers withing a cycle
-  New tests added
- [Task](https://rsklabs.atlassian.net/browse/TOK-454)

[TOK-454] feat: add veiw for estimated remaining rewards in cycle

---

test/BackersManagerRootstockCollective.t.sol

- Add tests to verify that allocations can be moved from one builder to the other when all votes are in use
- Backers might want to move votes from one builder to the other in a single transaction

chore: add tests to move allocations with allocateBatch

---

deployments/mainnet/mvp/contract_addresses.json
deployments/staging/mvp/contract_addresses.json
deployments/testnet/contract_addresses.json
deployments/testnet_qa/contract_addresses.json
deployments/testnet_qa_dapp/contract_addresses.json

chore: remove mvp deployment data

---

src/BuilderRegistryRootstockCollective.sol
test/GaugeRootstockCollective.t.sol
test/SetBuilderRewardReceiver.t.sol

fix: typo in approveBuilderRewardReceiverReplacement

---

test/invariant/BaseInvariants.sol
test/invariant/DistributionDurationInvariants.t.sol
test/invariant/handlers/DistributionDurationHandler.sol

- (describe the changes)
- (the reason these changes are wanted)
- (describe how to test the changes included)
- (optional: include links to other issues, PRs, tickets, etc)

Add distribution duration invariant test

---

test/BackersManagerRootstockCollective.t.sol
test/BuilderRegistryRootstockCollective.t.sol
test/GaugeRootstockCollective.t.sol
test/HaltedBuilderBehavior.t.sol
test/integration/DifferentRewardPercentages.t.sol

- Add some missing checks in unit tests and some integration tests
- [Ticket](https://rsklabs.atlassian.net/browse/TOK-136)

[TOK-136] Test: add missing tests from QA regression

---

README.md
specs/CONTRACTS.md
specs/SPECIFICATION.md

- Minor docs formating
- add links from README
- fix TODO adding missing link
- Why not?
- juet Review

Minor doc changes

---

src/backersManager/BackersManagerRootstockCollective.sol
test/BackersManagerRootstockCollective.t.sol

- Allow distributing without allocations
- Division error if there are builders and the total allocation is 0
- [TOK-490](https://rsklabs.atlassian.net/browse/TOK-490)

TOK-490/deadlock

---

specs/SPECIFICATION.md

- describe the rewards missing
- it was unclear for the security reviewers

TOK-516: add the rewards missing part

---

.env.31.fork
src/builderRegistry/BuilderRegistryRootstockCollective.sol
test/migrationForkV2/BuilderRegistryMigrationV2Fork.t.sol

- Fix halted gauges not being migrated

fix: migrate halted gauges

---

deployments/testnet_qa_dapp/contract_addresses.json
script/migrations/v2/MigrationV2.s.sol
script/script_utils/OutputWriter.s.sol
src/migrations/v2/MigrationV2.sol
test/GaugeRootstockCollective.t.sol
test/migrationForkV2/BackersManagerUpgradeV2Fork.t.sol
test/migrationForkV2/BuilderRegistryMigrationV2Fork.t.sol
test/migrationForkV2/GaugesUpgradeV2Fork.t.sol
test/migrationForkV2/MigrationSetupV2Fork.t.sol

Improve the migration
- perform setup operations at migration construction
- allow migration contract upgrader revert
- save deployment data

Improve v2 migration flow

---

package.json
script/verify.sh

- add script for automatic verification in blockscout

chore: automatic verification blockscout

---

deployments/mainnet/contract_addresses.json

- update mainnet v2 migration addresses

chore: update mainnet v2 migration addresses

---

README.md
src/backersManager/BackersManagerRootstockCollective.sol
src/gauge/GaugeRootstockCollective.sol

- document supported reward tokens, to fix RSCR-03 from the security report
- [Jira ticket](https://rsklabs.atlassian.net/jira/software/projects/TOK/boards/267?assignee=712020%3A42dabdd3-0b32-4060-be21-62cfd46a1751&selectedIssue=TOK-636)

TOK-636: detail supported reward tokens

---

.github/dependabot.yml
.github/workflows/ci.yml
.github/workflows/dependency-review.yml
.github/workflows/docgen.yml
.github/workflows/qa.deploy.yml
.github/workflows/scorecards.yml
.github/workflows/slither.yml
.github/workflows/staging.deploy.yaml
.github/workflows/test-deep.yml
README.md

**Implement Scorecard**
✅ Add scorecard workflow
❌  Add codeql workflow: codeql does not support solidity
✅ Add dependency-check workflow
✅ Add dependabot configuration
❌ Add fuzzing test: repo has fuzzing tests implemented, but not using a recognizedfuzzing supported framework
✅ Fix workflow permissions
✅  Bump action versions
✅  Add Scorecard badge on README file: the link will only work once merged to the default branch
- [Jira](https://rsklabs.atlassian.net/jira/software/projects/TOK/boards/267?label=sc&selectedIssue=TOK-613)

TOK-613: Implement Scorecard

---

deployments/dev/contract_addresses.json

- Update testnet dev env deployments addresses
IMPORTANT: I found a bit confusing all the environments, for example which environment in the dapp corresponds to the sc environment. Please confirm this is the right deployment addresses path that corresponds to the the dapp dev environment

chore: deploy testnet dev env

---

src/backersManager/BackersManagerRootstockCollective.sol
src/builderRegistry/BuilderRegistryRootstockCollective.sol

- Rename `validatedWhitelisted`
- The name is confusing
- [TOK-683](https://rsklabs.atlassian.net/browse/TOK-683)

TOK-683/validateWhitelisted-name

---

script/Deploy.s.sol
specs/PERMISSIONS.md
specs/SPECIFICATION.md
src/backersManager/BackersManagerRootstockCollective.sol
src/builderRegistry/BuilderRegistryRootstockCollective.sol
test/BackersManagerRootstockCollective.t.sol
test/BaseTest.sol
test/BuilderRegistryRootstockCollective.t.sol
test/upgradeability/Initialization.t.sol

- Renaming PR divided for each related change. This PR contains the builder renaming change from `activated` to `intialised`

Tok 535/improve naming initialised

---

README.md
docs/src/README.md
specs/PERMISSIONS.md
specs/SPECIFICATION.md
src/backersManager/BackersManagerRootstockCollective.sol
src/builderRegistry/BuilderRegistryRootstockCollective.sol
test/BuilderRegistryRootstockCollective.t.sol
test/CommunityBanBuilder.t.sol
test/invariant/BuilderInvariants.t.sol

- Renaming PR divided for each related change. This PR contains the builder renaming change from `dewhitelist` to `community ban`

Tok 535/improve naming dewhitelist

---

src/backersManager/BackersManagerRootstockCollective.sol
src/builderRegistry/BuilderRegistryRootstockCollective.sol
test/BuilderRegistryRootstockCollective.t.sol
test/governance/changers/CommunityApproveBuilderChanger.t.sol

- Remove unnecessary code
- Fix typos

TOK-535/improve_misc

---

.github/workflows/foundry-gas-diff.yml

- Add gh to compare functions gas costs with the base branch of a PR. The gas differences (if any) are written as a sticky comment.

feat: gha to compare gas costs

---

src/backersManager/BackersManagerRootstockCollective.sol
src/builderRegistry/BuilderRegistryRootstockCollective.sol
test/BuilderRegistryRootstockCollective.t.sol

- Reduce amount of gauge external calls
- Reduce gas cost
- Old
- New
- [TOK-700](https://rsklabs.atlassian.net/browse/TOK-700)

TOK-700/request-multiple-gauges

---

src/backersManager/BackersManagerRootstockCollective.sol
src/governance/GovernanceManagerRootstockCollective.sol
src/interfaces/IGovernanceManagerRootstockCollective.sol
test/BackersManagerRootstockCollective.t.sol
test/BaseTest.sol
test/governance/GovernanceManagerRootstockCollective.t.sol

- Adds a new role
- use the role for `updateMaxDistributionsPerBatch` 
- Resolves [TOK-707](https://rsklabs.atlassian.net/browse/TOK-707)

TOK-707: add configurator role

---

src/builderRegistry/BuilderRegistryRootstockCollective.sol

-  Dewhitelist builder function
- Maintain compatibility
-  [TOK-702](https://rsklabs.atlassian.net/browse/TOK-702)

TOK-702/sc-improve-naming

---

src/RewardDistributorRootstockCollective.sol
test/RewardDistributorRootstockCollective.t.sol

- allow any address to fund backers manager once per cycle with the default amount
- [TOK-706](https://rsklabs.atlassian.net/jira/software/projects/TOK/boards/267?assignee=712020%3A42dabdd3-0b32-4060-be21-62cfd46a1751&selectedIssue=TOK-706)
- [investigation notion](https://www.notion.so/iovlabs/TOK-578-Simplify-the-fund-distribute-steps-184c132873f980d59bc4f13a97bfd8c9?showMoveTo=true&saveParent=true)

Tok 706/cycle distribution simplification
