RootstockCollective/collective-rewards-sc

src/BuilderRegistry.sol
src/SponsorsManager.sol

- Give full allowance to whitelisted gauges instead of approve them on each distribution
Before
After

feat: give full rewardToken allowance to whitelisted gauges

---

docs/src/src/BuilderRegistry.sol/abstract.BuilderRegistry.md
docs/src/src/EpochTimeKeeper.sol/abstract.EpochTimeKeeper.md
docs/src/src/RewardDistributor.sol/contract.RewardDistributor.md
docs/src/src/SponsorsManager.sol/contract.SponsorsManager.md
docs/src/src/gauge/Gauge.sol/contract.Gauge.md
docs/src/src/gauge/GaugeBeacon.sol/contract.GaugeBeacon.md
docs/src/src/gauge/GaugeFactory.sol/contract.GaugeFactory.md
docs/src/src/governance/ChangeExecutorRootstockCollective.sol/contract.ChangeExecutorRootstockCollective.md
docs/src/src/governance/Governed.sol/abstract.Governed.md
docs/src/src/governance/Upgradeable.sol/abstract.Upgradeable.md
docs/src/src/governance/changerTemplates/WhitelistBuilderChangerTemplate.sol/contract.WhitelistBuilderChangerTemplate.md
docs/src/src/interfaces/IChangeContractRootstockCollective.sol/interface.IChangeContractRootstockCollective.md
docs/src/src/interfaces/IChangeExecutorRootstockCollective.sol/interface.IChangeExecutorRootstockCollective.md
docs/src/src/interfaces/ISponsorsManager.sol/interface.ISponsorsManager.md
docs/src/src/libraries/UtilsLib.sol/library.UtilsLib.md
docs/src/src/mvp/SimplifiedRewardDistributorRootstockCollective.sol/contract.SimplifiedRewardDistributorRootstockCollective.md
test/Gauge.t.sol

- `SponsorsManager` is used as incentivizer in several tests, but approving `rewardToken`s for incentives overlaps with max reward approval in whitelisting process. Since `SponsorsManager` won't be incentivizing gauges directly in real life, it's safe to simply remove it from the tests without taking any more precautions

fix: remove SponsorsManager as incentivizer in tests

---

foundry.toml

-lower the CI test verbosity
- it's "polluting" the output too much after we added invariants: see this foe example: https://github.com/RootstockCollective/collective-rewards-sc/actions/runs/11684901949/job/32537136636?pr=95
- Run the CI test job
- Not linked with any Jira ticket

Lower ci verbosity

---

script/Deploy.s.sol

- Include env vars when deploying GovernanceManager from the main script
- To follow the same approach used for the others

fix: include params when deploying GovernanceManager from main script

---

src/BackersManagerRootstockCollective.sol
test/StakingTokenWithdrawability.t.sol
test/mock/StakingTokenMock.sol

After [this](https://github.com/RootstockCollective/dao-contracts-private/pull/1#discussion_r1829016269) interaction, DAO team invert the order on how the `canWithdraw` function is invoke from the stRif to the CRC. After this change, we need to adjust accordingly.
- All stRif movements test cases should still be valid, with the only difference being that trying to send mode balance that what you have, should fail with default ERC20 error now.
- https://rsklabs.atlassian.net/browse/TOK-465
- StRif PR: https://github.com/RootstockCollective/dao-contracts-private/pull/1

Adjust strif canWithdraw interaction

---

.github/workflows/test-deep.yml

- change the deep test job name
- so we can remove it from the required checks (at the moment we have 2 tests jobs, so we either enable or disable both)

chore: change deep test job name

---

src/BackersManagerRootstockCollective.sol
src/BuilderRegistryRootstockCollective.sol
src/gauge/GaugeRootstockCollective.sol
test/BuilderRegistryRootstockCollective.t.sol
test/GaugeRootstockCollective.t.sol
test/MigrateBuilder.t.sol
test/RevokeBuilder.t.sol
test/SetBackerRewardPercentage.t.sol

- In `BuilderRegistry` smart contract, there is a variable named `builderRewardPercentage` which does not represent what the names try to represent, we are renaming it to `backerRewardPercentage` to align with the whitepaper and align what it represents. 
- [Task](https://rsklabs.atlassian.net/browse/TOK-485)

[TOK-481] Rename builderRewardPercentage to backerRewardPercentage

---

src/BackersManagerRootstockCollective.sol
test/BackersManagerRootstockCollective.t.sol

- If there are no active gauges (there are no gauges or they are all halted), revert with an error when trying to call `notifyRewardAmount` from the `backersManager` contract
-  As raised in RSCR-04 from the last security report, if a distribution happens with no active gauges then the existing rewards get locked in the `backersManager` contract and not taken into account for following distributions. 
OBS: while this fix prevents the foundation from sending rewards and executing the distribution (the same as when we have no allocations) it doesn't prevent rewards from getting locked in a scenario like this:
1. rewards are sent to the `backersManager` with active gauges
2. all gauges get revoked
3. someone starts directly the distribution (not from the `rewardsDistributor` but form the …

[ TOK-481] RSCR-04: Don't allow sending rewards to backersManager with no active gauges

---

script/Deploy.s.sol

Adds the previous missing `broadcast()` to actually sign and bradcast the Tx to the network
Collective rewards not being initialized on deployment with function `initializeCollectiveRewardsAddresses`, the call was there, but the Tx wasn't.
Deploy on testnet and verify that now the contract is initialized with backers address.
https://rsklabs.atlassian.net/browse/TOK-492
https://book.getfoundry.sh/cheatcodes/broadcast

[TOK-492] fix: collective rewards not beinig initialized on deploy

---

test/invariant/BaseInvariants.sol
test/invariant/RewardInvariants.t.sol

Introduce dust tolerance to gauge balance on invariant tests. 
As the deep run might include several cycle distributions, there might be duut left from previous ones.  
let it :fire: those :computer: :computer:

Add dust tolerance on invariants

---

.solhint.test.json
test/SetBackerRewardPercentage.t.sol
test/governance/GovernanceManagerRootstockCollective.t.sol

Turns off two lint rules that are not that important on testing context:
- "no-empty-blocks": "off",
-  "one-contract-per-file": "
And fixes/addresses same other trivial warning.
To clear the shell output from unnecessary warnings.
`bun run lint`

Relax testing solhint rules

---

src/BackersManagerRootstockCollective.sol
src/gauge/GaugeRootstockCollective.sol

- It is required to mention that only standard ERC20 tokens must be used as reward Token
- The external auditors have supposed a scenario where a non-standard token could break our rewards logic

TOK-480: add comment on top of rewardToken

---

package.json

Removes legacy mvp deploymwnt script
It's not longer used nor functional
Everything should be working as expected

Remove legacy mvp deployment script

---

script/BackersManagerRootstockCollective.s.sol
script/Deploy.s.sol
src/CycleTimeKeeperRootstockCollective.sol
src/RewardDistributorRootstockCollective.sol
src/backersManager/BackersManagerRootstockCollective.sol
src/backersManager/BuilderRegistryRootstockCollective.sol
src/backersManager/CycleTimeKeeperRootstockCollective.sol
src/gauge/GaugeRootstockCollective.sol
src/governance/changerTemplates/CommunityApproveBuilderChangerTemplateRootstockCollective.sol
src/interfaces/IBackersManagerRootstockCollective.sol
test/BackersManagerRootstockCollective.t.sol
test/BaseTest.sol
test/BuilderRegistryRootstockCollective.t.sol
test/MigrateBuilder.t.sol
test/SetBackerRewardPercentage.t.sol
test/SetBuilderRewardReceiver.t.sol
test/SetCycleDuration.t.sol
test/SetDistributionDuration.t.sol
test/invariant/handlers/BaseHandler.sol
test/mock/UpgradesMocks.sol

- Makes BackerManager inherit from Interface
- Moves all BackerManager related contract files to `backerManager` folder
- makes de code more consistence and clear
- all test should pass

Code reorg

---

README.md

- Removes foundry max version requirement from docs (after testing that deployment works with the latest)
- deployment to testnet should succeed
- https://rsklabs.atlassian.net/browse/TOK-513

chore(docs): remove max foundry version limit

---

src/backersManager/BackersManagerRootstockCollective.sol
test/OptOutRewardsBehaviour.t.sol

- We need to introduce a Rewards opt-out mechanism in CR enabling users to voluntarily opt-in to restrict their wallets from receiving rewards or making allocations in Collective Rewards.
- This feature ensures transparency and prevents potential conflicts of interest.
- Unit testing
- [Jira ticket](https://rsklabs.atlassian.net/jira/software/projects/TOK/boards/267?assignee=712020%3A42dabdd3-0b32-4060-be21-62cfd46a1751&selectedIssue=TOK-568)

TOK-568: allow backer rewards opt out

---

src/backersManager/BackersManagerRootstockCollective.sol
src/builderRegistry/BuilderRegistryRootstockCollective.sol
test/BuilderRegistryRootstockCollective.t.sol
test/governance/changers/CommunityApproveBuilderChanger.t.sol
test/migrationForkV2/BackersManagerUpgradeV2Fork.t.sol

- Maintain the community approval proposal interface in the BackersManager, to avoid failing proposals while migrating
- To ensure that ongoing community approval proposals during migration can still be successfully executed
- unit tests
- [Jira ticket](https://rsklabs.atlassian.net/jira/software/projects/TOK/boards/267?assignee=712020%3A42dabdd3-0b32-4060-be21-62cfd46a1751&selectedIssue=TOK-627)

feat: ensure v1 community approval compatibility

---

src/backersManager/BackersManagerRootstockCollective.sol
test/BackersManagerRootstockCollective.t.sol
test/mock/ERC20Mock.sol

Handling the scenarios of erc20 token returning false.
In most cases, this will not happen, as almost all erc20 standard tokens have their built-in reversion logic, but still, if the given token returns false on the approval, the contract will revert with the corresponding message.
- There are not any separate unit tests written for this function as it is used by other contracts' functions that are being tested.

Tok 679/erc20 approve not validated

---

src/governance/GovernanceManagerRootstockCollective.sol
test/governance/GovernanceManagerRootstockCollective.t.sol

- Add `onlyValidAddress` to `_updateUpgrader` in governor
- If an invalid address is set for upgrader, the contract might become un-upgradeable
- bun run test
- [TOK-682](https://rsklabs.atlassian.net/browse/TOK-682)

TOK-682/potential-zero-address-update

---

specs/CONTRACTS.md
specs/SPECIFICATION.md
src/builderRegistry/BuilderRegistryRootstockCollective.sol
test/BackersManagerRootstockCollective.t.sol
test/BuilderRegistryRootstockCollective.t.sol
test/PauseBuilder.t.sol
test/PauseSelfBuilder.t.sol
test/RevokeKYC.t.sol
test/fuzz/SelfPauseBuilder.sol
test/integration/SkipDistribution.t.sol
test/invariant/handlers/BuilderHandler.sol

- Renaming PR divided for each related change. This PR contains the builder renaming change from `revoke` to `pauseSelf` and `permit` to `unpauseSelf`

Tok 535/improve naming self paused unpaused

---

specs/CONTRACTS.md
specs/PERMISSIONS.md
src/builderRegistry/BuilderRegistryRootstockCollective.sol
src/interfaces/IBackersManagerRootstockCollective.sol
test/BuilderRegistryRootstockCollective.t.sol
test/GaugeRootstockCollective.t.sol
test/RewardReceiverUpdate.t.sol
test/SetBuilderRewardReceiver.t.sol

- Renaming PR divided for each related change. This PR contains the builder renaming change from `reward receiver replacement` to `reward receiver updates`

Tok 535/improve naming reward receiver

---

src/backersManager/BackersManagerRootstockCollective.sol
src/builderRegistry/BuilderRegistryRootstockCollective.sol

- Reduce the amount of external calls in the resume and halt gauges methods
- Going back and forth make the code complex
- Reduce gas cost
- Old
- New
- [TOK-698](https://rsklabs.atlassian.net/browse/TOK-698)

TOK-698/halt-resume-gauges

---

src/backersManager/BackersManagerRootstockCollective.sol
src/builderRegistry/BuilderRegistryRootstockCollective.sol

- reduce the number of external calls made from the `BackersManager` to the `BuilderRegistry` by creating a single function for that role 
- to reduce gas cost
- `forge test`

TOK-699_reduce-external-calls-in-BackersManager.allocate

---

specs/PERMISSIONS.md

- Describe the configurator role
- Description is missing

docs: add configurator description
